### ISSUE TITLE
Port UpperCaseQuiz activity from Learning Greek

### ISSUE THREAD

**Issue by paltman** [pinax/lms-activities-demo#5]
See: https://github.com/jtauber/learning-greek/blob/master/learning_greek/activities/alphabet.py#L11

**Comment by jtauber** [comment]
I was going to suggest closing this as you've already done a TwoChoiceQuiz but I actually think it's worthwhile having a different example like this that isn't a fixed list but has randomization, duplicate removal, etc.

**Comment by jtauber** [comment]
Given other examples now have this, I'm going to close it.
